import { Post } from './types';

export const mockPosts: Post[] = [
  {
    id: '1',
    username: 'ZeroDay',
    handle: '@zero_day_hunter',
    avatar: '🔥',
    timestamp: '2m ago',
    content: 'Just discovered a new CVE in a popular web framework. Responsible disclosure in progress. The vulnerability affects authentication bypass mechanisms. #SecurityResearch #CVE #BugBounty',
    likes: 42,
    reposts: 15,
    comments: 8,
    tags: ['SecurityResearch', 'CVE', 'BugBounty'],
    isLiked: false,
    isReposted: false,
    reputation: 98,
    verified: true,
    category: 'research',
    isBookmarked: false
  },
  {
    id: '2',
    username: 'ByteQueen',
    handle: '@byte_queen',
    avatar: '👑',
    timestamp: '15m ago',
    content: 'New exploit chain for privilege escalation on Linux systems. Check out my latest research paper! 📄 Remember: always test in controlled environments only.',
    imageUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAwIiBoZWlnaHQ9IjI4MCIgdmlld0JveD0iMCAwIDUwMCAyODAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iMjgwIiBmaWxsPSIjMWExYTFhIi8+Cjx0ZXh0IHg9IjI1MCIgeT0iMTUwIiBmb250LWZhbWlseT0ibW9ub3NwYWNlIiBmb250LXNpemU9IjE4IiBmaWxsPSIjMDBmZjAwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5MaW51eCBFeHBsb2l0IFJlc2VhcmNoPC90ZXh0Pgo8L3N2Zz4K',
    likes: 156,
    reposts: 73,
    comments: 24,
    tags: ['Linux', 'PrivEsc', 'Research'],
    isLiked: true,
    isReposted: false,
    reputation: 92,
    verified: true,
    category: 'exploit',
    isBookmarked: true
  },
  {
    id: '3',
    username: 'CodeBreaker',
    handle: '@code_breaker_42',
    avatar: '💻',
    timestamp: '1h ago',
    content: 'Working on a new cryptography challenge. The encryption algorithm uses a combination of RSA and AES. Anyone want to collaborate? DM me! #Crypto #Challenge',
    likes: 89,
    reposts: 34,
    comments: 16,
    tags: ['Crypto', 'Challenge', 'RSA', 'AES'],
    isLiked: false,
    isReposted: true,
    reputation: 87,
    category: 'question',
    isBookmarked: false
  },
  {
    id: '4',
    username: 'NetStalker',
    handle: '@net_stalker',
    avatar: '🕷️',
    timestamp: '3h ago',
    content: 'Network reconnaissance tools comparison: Nmap vs Masscan vs Zmap. Performance benchmarks and stealth capabilities analyzed. Full thread below 🧵',
    imageUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAwIiBoZWlnaHQ9IjI4MCIgdmlld0JveD0iMCAwIDUwMCAyODAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iMjgwIiBmaWxsPSIjMGYxNzJhIi8+Cjx0ZXh0IHg9IjI1MCIgeT0iMTMwIiBmb250LWZhbWlseT0ibW9ub3NwYWNlIiBmb250LXNpemU9IjE2IiBmaWxsPSIjMDBkNGZmIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5OZXR3b3JrIFNjYW5uaW5nPC90ZXh0Pgo8dGV4dCB4PSIyNTAiIHk9IjE2MCIgZm9udC1mYW1pbHk9Im1vbm9zcGFjZSIgZm9udC1zaXplPSIxNCIgZmlsbD0iIzAwZDRmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+Q29tcGFyaXNvbjwvdGV4dD4KPC9zdmc+Cg==',
    likes: 234,
    reposts: 98,
    comments: 45,
    tags: ['Nmap', 'Recon', 'NetworkSecurity'],
    isLiked: true,
    isReposted: false,
    reputation: 94,
    verified: true,
    category: 'tutorial',
    isBookmarked: true
  },
  {
    id: '5',
    username: 'PhishHunter',
    handle: '@phish_hunter',
    avatar: '🎣',
    timestamp: '5h ago',
    content: 'Detected a new phishing campaign targeting crypto exchanges. IOCs shared with the community. Stay vigilant! 🚨 #Phishing #ThreatIntel #CyberSecurity',
    likes: 312,
    reposts: 187,
    comments: 52,
    tags: ['Phishing', 'ThreatIntel', 'CyberSecurity'],
    isLiked: false,
    isReposted: false,
    reputation: 96,
    verified: true,
    category: 'news',
    isBookmarked: false
  },
  {
    id: '6',
    username: 'Anonymous404',
    handle: '@anon_404',
    avatar: '👤',
    timestamp: '8h ago',
    content: 'Just finished my OSCP certification! 🎉 The journey was tough but worth it. Here are my top 5 tips for anyone preparing for the exam... Thread 🧵',
    likes: 421,
    reposts: 203,
    comments: 67,
    tags: ['OSCP', 'Certification', 'Tips'],
    isLiked: true,
    isReposted: false,
    reputation: 78,
    category: 'news',
    isBookmarked: true
  }
];
